[package]
name = "file-saver"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-file = "0.2"
gloo-utils = "0.1"
log = "0.4"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
web-sys = {version = "0.3", features = ["Document", "HtmlAnchorElement"]}
yew = {version = "0.20", features = ["csr"]}
